### ISSUE TITLE
Convert UML to ER Model

### ISSUE THREAD

**Issue by JDziurlaj** [HiltonRoscoe/umm_templates#3]
Write a script that can be executed by Oracle Data Modeler to create a logical data model. Steps:

1. Create Domains from UML Enumerations
2. Create Entities from UML Classes
3. Create Attributes from UML Attributes
4. Create relations from associations

## Attributes

Certain attributes in UML will need to be converted to relationships, because they are non-atomic (and thus a normal form violation)

- 0..1 -> Optional Attribute (default)
- 1 -> Mandatory Attribute
- 1..* -> Non-identifying Foreign Key (easiest), although an identifying FK is probably closer to the relationship in UML. 

## Relations

- Do not map composing relationships

## Todos

- [x] Handle multiple primitives
- [x] Handle attributes vs associations correctly
- [x] Improve primitive handling
- [x] Handle primitive associations `1..*` (relation AND attribute must be required)
- [x] Fix FK names. They can come from fkRole DP, but has side effects.
  - [ ] Fix FK for deep type hierachies, they don't pull the parent FK. This may become a problem if we allow multiple engineering approaches!
 - [x] Fix writeinimage being UNKNOWN instead of an association.
- [ ] Fix issue with non-semantic directed compositions
- [x] Fix issue with generated table not accounting for role name (e.g. `CandidateSelection` -> `EndorsementParty`)
- [x] Fix issue with composite foreign keys having duplicate names when using `fkRole`
## Checks
> There is a bug with ODM that causes the relationship lines to appear incorrectly. Use display labels to force a refresh.

- [x] Proper directed composition
- [x] Proper directed association
- [ ] Test ERR Oracle DDL
- [ ] Test ERR SQL Server DDL
- [ ] Test CVR Oracle DDL
- [ ] Test CVR SQL Server DDL
