### ISSUE TITLE
XML<->JSON Metaissue

### ISSUE THREAD

**Issue by JDziurlaj** [HiltonRoscoe/umm_templates#8]
See `CDFPrototype/jsonxmlconv` for WIP
- [ ] Validate ERR -> XML XSL
- [ ] Validate CVR ->XML XSL
- [ ] Write CVR -> JSON XSL
- [ ] Write ERR -> JSON XSL
- [ ] Validate ERR -> JSON XSL
- [ ] Validate CVR -> JSON XSL
- [ ] Writeup Documentation
